/*
 * Copyright (C) 2022 marin
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cooperativa.vistas;

import com.opencsv.CSVReader;
import com.opencsv.CSVWriter;
import com.opencsv.exceptions.CsvValidationException;
import cooperativa.objetos.*;
import static cooperativa.principal.Base.cuerpoContenedor;
import static cooperativa.principal.Base.refrescaVista;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;  
import java.time.format.DateTimeFormatter;  
/**
 *
 * @author marin
 */
public class CrearMovimiento extends javax.swing.JPanel {
    
    private int lastId = -1;
    private ArrayList<Concepto> Conceptos = new ArrayList();
    private ArrayList<Persona> Personas = new ArrayList();
    private ArrayList<Movimiento> Movimientos = new ArrayList();
    
    /**
     * Creates new form Inicio
     */
    public CrearMovimiento() {
        
        initComponents();
        
        FechaVal.setText(java.time.LocalDate.now().toString());
        
        CSVReader origenConceptos, origenPersona, origenMovimientos;
        
        try {
            origenPersona = new CSVReader(new FileReader("personas.csv"));
            String[] linea = null;
            try {
                while ((linea = origenPersona.readNext()) != null) {
                    comboIdPersona.addItem(linea[0]);
                }
            } catch (IOException | CsvValidationException ex) {
                Logger.getLogger(CrearMovimiento.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CrearMovimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            origenConceptos = new CSVReader(new FileReader("conceptos.csv"));
            String[] linea = null;
            try {
                while ((linea = origenConceptos.readNext()) != null) {
                    comboIdConcepto.addItem(linea[0]);
                }
            } catch (IOException | CsvValidationException ex) {
                Logger.getLogger(CrearMovimiento.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CrearMovimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            origenMovimientos = new CSVReader(new FileReader("movimientos.csv"));
            String[] linea = null;
            try {
                while ((linea = origenMovimientos.readNext()) != null) {
                    Movimientos.add(new Movimiento(Integer.parseInt(linea[0]), linea[1], Integer.parseInt(linea[2]), Integer.parseInt(linea[3]), linea[4], Double.parseDouble(linea[5]), linea[6]));
                }
            } catch (IOException | CsvValidationException ex) {
                Logger.getLogger(CrearMovimiento.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CrearMovimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (Movimiento tipo : Movimientos) {
            if(lastId < tipo.getIdPersona()) {
                lastId = tipo.getIdPersona();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadio = new javax.swing.ButtonGroup();
        Panel = new javax.swing.JPanel();
        idPersona = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        statusVal = new javax.swing.JRadioButton();
        statusVal1 = new javax.swing.JRadioButton();
        statusVal2 = new javax.swing.JRadioButton();
        statusVal3 = new javax.swing.JRadioButton();
        comboIdPersona = new javax.swing.JComboBox<>();
        DetalleVal = new javax.swing.JTextField();
        Detalle = new javax.swing.JLabel();
        Importe = new javax.swing.JLabel();
        ImporteVal = new javax.swing.JTextField();
        FechaVal = new javax.swing.JTextField();
        Fecha = new javax.swing.JLabel();
        idConcepto = new javax.swing.JLabel();
        comboIdConcepto = new javax.swing.JComboBox<>();
        Título = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(710, 580));
        setMinimumSize(new java.awt.Dimension(710, 580));
        setPreferredSize(new java.awt.Dimension(710, 580));

        idPersona.setText("Persona");

        status.setText("Estado");

        grupoRadio.add(statusVal);
        statusVal.setSelected(true);
        statusVal.setText("Inactivo");
        statusVal.setActionCommand("0");
        statusVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusValActionPerformed(evt);
            }
        });

        grupoRadio.add(statusVal1);
        statusVal1.setText("Revisión");
        statusVal1.setActionCommand("1");

        grupoRadio.add(statusVal2);
        statusVal2.setText("Activo");
        statusVal2.setActionCommand("2");
        statusVal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusVal2ActionPerformed(evt);
            }
        });

        grupoRadio.add(statusVal3);
        statusVal3.setText("Bloqueado");
        statusVal3.setActionCommand("3");

        comboIdPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIdPersonaActionPerformed(evt);
            }
        });

        Detalle.setText("Detalle");

        Importe.setText("Importe");

        Fecha.setText("Fecha");

        idConcepto.setText("Concepto");

        comboIdConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIdConceptoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Importe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idPersona, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(status, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                                .addComponent(statusVal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statusVal1)
                                .addGap(12, 12, 12)
                                .addComponent(statusVal2)
                                .addGap(12, 12, 12)
                                .addComponent(statusVal3))
                            .addComponent(Detalle, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FechaVal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImporteVal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboIdPersona, javax.swing.GroupLayout.Alignment.LEADING, 0, 630, Short.MAX_VALUE)
                            .addComponent(DetalleVal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboIdConcepto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idConcepto)
                            .addComponent(Fecha))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Fecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FechaVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idPersona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboIdPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idConcepto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboIdConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Detalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DetalleVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Importe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ImporteVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusVal)
                    .addComponent(statusVal1)
                    .addComponent(statusVal2)
                    .addComponent(statusVal3))
                .addGap(20, 20, 20))
        );

        Título.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Título.setText("Crear movimiento");

        btnCrear.setText("Crear movimiento");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar y volver");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Título, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrear)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCancelar)
                    .addComponent(Título))
                .addGap(11, 11, 11)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(btnCrear)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void statusValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusValActionPerformed
    }//GEN-LAST:event_statusValActionPerformed

    private void statusVal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusVal2ActionPerformed
    }//GEN-LAST:event_statusVal2ActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        if(comboIdPersona.getModel().getSelectedItem().equals("") || DetalleVal.getText().equals("") || ImporteVal.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Uno de los campos se encuentra vacío, verifica de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String statusId = "";
            String idPersona = (String)comboIdPersona.getSelectedItem();
            String idConcepto = (String)comboIdConcepto.getSelectedItem();
            
            for (Enumeration<AbstractButton> buttons = grupoRadio.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();
                if (button.isSelected()) {
                    statusId = button.getActionCommand();
                }
            }
            
            Movimientos.add(new Movimiento(lastId + 1, FechaVal.getText(), Integer.parseInt(idPersona), Integer.parseInt(idConcepto), DetalleVal.getText(), Double.parseDouble(ImporteVal.getText()), statusId));
            
            try {
                CSVWriter destino = new CSVWriter(new FileWriter("movimientos.csv", false));
                
                for (Movimiento tipo : Movimientos) {
                    String [] datos = tipo.getArray();
                    destino.writeNext(datos);
                }
                
                destino.close();
                
                JOptionPane.showMessageDialog(null, "El movimiento se ha guardado exitosamente");
                
                refrescaVista(new VerMovimientos(), "", "");
                
            } catch (IOException ex) {
                Logger.getLogger(CrearMovimiento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        refrescaVista(new VerMovimientos(), "", "");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comboIdPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIdPersonaActionPerformed
        
    }//GEN-LAST:event_comboIdPersonaActionPerformed

    private void comboIdConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIdConceptoActionPerformed
        
    }//GEN-LAST:event_comboIdConceptoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Detalle;
    private javax.swing.JTextField DetalleVal;
    private javax.swing.JLabel Fecha;
    private javax.swing.JTextField FechaVal;
    private javax.swing.JLabel Importe;
    private javax.swing.JTextField ImporteVal;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Título;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox<String> comboIdConcepto;
    private javax.swing.JComboBox<String> comboIdPersona;
    private javax.swing.ButtonGroup grupoRadio;
    private javax.swing.JLabel idConcepto;
    private javax.swing.JLabel idPersona;
    private javax.swing.JLabel status;
    private javax.swing.JRadioButton statusVal;
    private javax.swing.JRadioButton statusVal1;
    private javax.swing.JRadioButton statusVal2;
    private javax.swing.JRadioButton statusVal3;
    // End of variables declaration//GEN-END:variables
}
