/*
 * Copyright (C) 2022 marin
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cooperativa.vistas;

import com.opencsv.CSVReader;
import com.opencsv.CSVWriter;
import com.opencsv.exceptions.CsvValidationException;
import cooperativa.objetos.TipoPersona;
import static cooperativa.principal.Base.cuerpoContenedor;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author marin
 */
public class CrearTipoPersonas extends javax.swing.JPanel {
    
    private int lastId = -1;
    private ArrayList<TipoPersona> TipoPersonas = new ArrayList();
    
    /**
     * Creates new form Inicio
     */
    public CrearTipoPersonas() {
        
        initComponents();
        
        CSVReader origen;
        
        try {
            origen = new CSVReader(new FileReader("tipopersonas.csv"));
            String[] linea = null;
            try {
                while ((linea = origen.readNext()) != null) {
                    TipoPersonas.add(new TipoPersona(Integer.parseInt(linea[0]), linea[1], linea[2]));
                }
            } catch (IOException | CsvValidationException ex) {
                Logger.getLogger(CrearTipoPersonas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CrearTipoPersonas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (TipoPersona tipo : TipoPersonas) {
            if(lastId < tipo.getIdTipoPersona()) {
                lastId = tipo.getIdTipoPersona();
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadio = new javax.swing.ButtonGroup();
        Título = new javax.swing.JLabel();
        BtnCrear = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        idTipoPersona = new javax.swing.JLabel();
        idTipoPersonaVal = new javax.swing.JTextField();
        status = new javax.swing.JLabel();
        statusVal = new javax.swing.JRadioButton();
        statusVal1 = new javax.swing.JRadioButton();
        statusVal2 = new javax.swing.JRadioButton();
        statusVal3 = new javax.swing.JRadioButton();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(710, 580));
        setMinimumSize(new java.awt.Dimension(710, 580));
        setPreferredSize(new java.awt.Dimension(710, 580));

        Título.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Título.setText("Crear tipo de persona");

        BtnCrear.setText("Crear ");

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        idTipoPersona.setText("Nombre del tipo de persona");

        status.setText("Estado");

        grupoRadio.add(statusVal);
        statusVal.setSelected(true);
        statusVal.setText("Inactivo");
        statusVal.setActionCommand("0");
        statusVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusValActionPerformed(evt);
            }
        });

        grupoRadio.add(statusVal1);
        statusVal1.setText("Revisión");
        statusVal1.setActionCommand("1");

        grupoRadio.add(statusVal2);
        statusVal2.setText("Activo");
        statusVal2.setActionCommand("2");
        statusVal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusVal2ActionPerformed(evt);
            }
        });

        grupoRadio.add(statusVal3);
        statusVal3.setText("Bloqueado");
        statusVal3.setActionCommand("3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTipoPersonaVal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTipoPersona)
                            .addComponent(status)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(statusVal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statusVal1)
                                .addGap(12, 12, 12)
                                .addComponent(statusVal2)
                                .addGap(12, 12, 12)
                                .addComponent(statusVal3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(idTipoPersona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTipoPersonaVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusVal)
                    .addComponent(statusVal1)
                    .addComponent(statusVal2)
                    .addComponent(statusVal3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnCrear.setText("Crear tipo de persona");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar y volver");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BtnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnCrear))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Título, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                                .addComponent(btnCancelar))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrear)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCancelar)
                    .addComponent(Título))
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrear)
                .addGap(434, 434, 434)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCrear)
                    .addComponent(BtnEliminar))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void statusValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusValActionPerformed
    }//GEN-LAST:event_statusValActionPerformed

    private void statusVal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusVal2ActionPerformed
    }//GEN-LAST:event_statusVal2ActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        System.out.println(idTipoPersonaVal.getText());
        if(idTipoPersonaVal.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un nombre, verifica de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String statusId = "";
            
            for (Enumeration<AbstractButton> buttons = grupoRadio.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();
                if (button.isSelected()) {
                    statusId = button.getActionCommand();
                }
            }
            
            TipoPersonas.add(new TipoPersona(lastId + 1, idTipoPersonaVal.getText(), statusId));
            
            try {
                CSVWriter destino = new CSVWriter(new FileWriter("tipopersonas.csv", false));
                
                for (TipoPersona tipo : TipoPersonas) {
                    String [] datos = tipo.getArray();
                    destino.writeNext(datos);
                }
                
                destino.close();
                
                JOptionPane.showMessageDialog(null, "El tipo de persona se ha guardado exitosamente");
                
                VerTipoPersonas vista = new VerTipoPersonas();
                vista.setSize(710, 580);
                vista.setLocation(0, 0);
                
                cuerpoContenedor.removeAll();
                cuerpoContenedor.add(vista);
                cuerpoContenedor.revalidate();
                cuerpoContenedor.repaint();
                
            } catch (IOException ex) {
                Logger.getLogger(CrearTipoPersonas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        VerTipoPersonas vista = new VerTipoPersonas();
        vista.setSize(710, 580);
        vista.setLocation(0, 0);

        cuerpoContenedor.removeAll();
        cuerpoContenedor.add(vista);
        cuerpoContenedor.revalidate();
        cuerpoContenedor.repaint();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrear;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JLabel Título;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.ButtonGroup grupoRadio;
    private javax.swing.JLabel idTipoPersona;
    private javax.swing.JTextField idTipoPersonaVal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel status;
    private javax.swing.JRadioButton statusVal;
    private javax.swing.JRadioButton statusVal1;
    private javax.swing.JRadioButton statusVal2;
    private javax.swing.JRadioButton statusVal3;
    // End of variables declaration//GEN-END:variables
}
